// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Toast } from "../components/ui/Toast";

// 💡 PASO 1: Importar el componente Header
// Asegúrate de que la ruta sea correcta (asumo que está en la carpeta 'components')
import Header from "../components/Header"; 
import FacebookPixel from "../components/FacebookPixel"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Cambié 'lang="en"' a 'lang="es"' ya que estás programando en español
    <html lang="es">
      <body
        className="font-sans antialiased"
      >
        
        {/* 💡 PASO 2: Colocar el Header antes del {children} */}
        {/* El Header aparecerá en la parte superior de todas las páginas */}
        <Header /> 
        
        {children}
        
        {/* 📊 Facebook Pixel para tracking */}
        <FacebookPixel />
        <Toast />
      </body>
    </html>
  );
}