-- Migracion segura de vistas fijas (articulos/insumos) a tipos configurables.
-- Se puede ejecutar completa en Supabase SQL Editor.
begin;

create table if not exists public.tipos_producto (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nombre text not null,
  activo boolean not null default true,
  protegido boolean not null default false,
  orden integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tipos_producto_slug_formato check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  constraint tipos_producto_nombre_no_vacio check (length(trim(nombre)) > 0)
);

insert into public.tipos_producto (slug, nombre, activo, protegido, orden)
values
  ('articulos', 'Artículos', true, true, 10),
  ('insumos', 'Insumos', true, true, 20)
on conflict (slug) do update
set protegido = true,
    activo = true,
    orden = excluded.orden;

-- Recupera tipos personalizados que la version temporal guardo en app_settings.
insert into public.tipos_producto (slug, nombre, activo, protegido, orden)
select
  item->>'slug',
  coalesce(nullif(trim(item->>'nombre'), ''), initcap(replace(item->>'slug', '-', ' '))),
  coalesce((item->>'activo')::boolean, true),
  coalesce((item->>'protegido')::boolean, false),
  coalesce((item->>'orden')::integer, 100)
from public.app_settings settings_row
cross join lateral jsonb_array_elements(
  case when jsonb_typeof(settings_row.settings) = 'array' then settings_row.settings else '[]'::jsonb end
) item
where settings_row.key = 'product_views'
  and coalesce(item->>'slug', '') ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
on conflict (slug) do update
set nombre = excluded.nombre,
    activo = excluded.activo,
    orden = excluded.orden;

-- Conserva cualquier valor historico que ya exista en productos.
insert into public.tipos_producto (slug, nombre, activo, protegido, orden)
select distinct
  lower(trim(p.vista_producto)),
  initcap(replace(lower(trim(p.vista_producto)), '-', ' ')),
  true,
  false,
  100
from public.productos p
where coalesce(trim(p.vista_producto), '') <> ''
  and lower(trim(p.vista_producto)) ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
on conflict (slug) do nothing;

update public.productos
set vista_producto = 'articulos'
where vista_producto is null
   or trim(vista_producto) = ''
   or lower(trim(vista_producto)) !~ '^[a-z0-9]+(-[a-z0-9]+)*$';

update public.productos set vista_producto = lower(trim(vista_producto));

-- Quita el CHECK anterior que solo aceptaba articulos e insumos.
do $$
declare constraint_row record;
begin
  for constraint_row in
    select conname
    from pg_constraint
    where conrelid = 'public.productos'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%vista_producto%'
  loop
    execute format('alter table public.productos drop constraint %I', constraint_row.conname);
  end loop;
end $$;

alter table public.productos alter column vista_producto set default 'articulos';
alter table public.productos alter column vista_producto set not null;

alter table public.productos drop constraint if exists productos_vista_producto_fkey;
alter table public.productos
  add constraint productos_vista_producto_fkey
  foreign key (vista_producto)
  references public.tipos_producto(slug)
  on update cascade
  on delete restrict;

create index if not exists idx_productos_vista_pais_sucursal
  on public.productos(vista_producto, pais_id, sucursal_id)
  where archivado = false;

create or replace function public.touch_tipos_producto_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_tipos_producto_updated_at on public.tipos_producto;
create trigger trg_tipos_producto_updated_at
before update on public.tipos_producto
for each row execute function public.touch_tipos_producto_updated_at();

alter table public.tipos_producto enable row level security;
drop policy if exists tipos_producto_public_read on public.tipos_producto;
create policy tipos_producto_public_read
on public.tipos_producto for select
to anon, authenticated
using (activo = true);

grant select on public.tipos_producto to anon, authenticated;

commit;

-- Comprobacion: debe devolver cero filas.
select p.user_id, p.nombre, p.vista_producto
from public.productos p
left join public.tipos_producto t on t.slug = p.vista_producto
where t.slug is null;
